let hotelList =  [{
    "_id": {
      "$oid": "6572d4a68b1ed834068ebc2f"
    },
    "price": "348",
    "name": "DoubleTree by Hilton Toronto Downtown",
    "location": "not found",
    "url": "https://www.momondo.ca/hotel-search/Chelsea-Hotel,Toronto,Toronto-c11592-h32729-details/2023-12-13/2023-12-14/2adults?psid=hHCkB37OEZ&pm=totaltaxes#overview",
    "reviewDescription": "Good",
    "score": "7.7",
    "reviewCount": "5,372 reviews",
    "noOfguests": "2",
    "city": "Toronto",
    "fromDate": "2023-12-13",
    "toDate": "2023-12-14",
    "overView": "A landmark hotel in the heart of downtown Toronto located at 108 Chestnut St; Toronto in the city’s business hub. Conveniently located close to major Government Offices, Nathan Phillips Square, City Hall, World Class Hospitals, Universities, US Consulate & Diplomatic Missions, Toronto's Eaton Centre, Yonge/Dundas Square, TTC subway, underground PATH, major attractions and points of interest. The hotel features 490 modern non-smoking guest rooms including 34 suites. The standard guestrooms consist of the choice of standard king, queen, or two double beds. The 26 two-room suites boast kitchenettes and separate living area, are ideal for extended stays or guests looking for additional space. The hotel also has 4 Junior Suites which have an open-concept layout with kitchenettes as well as 4 Executive Suites, all of which are located on the 25th and 26th floors. The suites are large enough to accommodate intimate corporate meetings or receptions. The hotel offers a concierge service, uniformed security patrol, secure underground guest parking, and an ATM located in the lobby. Guests can stay connected with complimentary high-speed internet access throughout the hotel and 24 hour open-concept business centre. Maintain your exercise regime in the complimentary 24-hour Precor fitness center, unwind in the sauna or take a dip in the heated indoor swimming pool. Changing facilities are equipped with lockers. A laundry room is situated on the Mezzanine Level for guest convenience. Dine-in or takeout at our new concept on-site Hemisphere's Restaurant for breakfast, lunch or dinner. Relax and enjoy light fare and cocktails with friends or colleagues in our Bistro lounge. Room service is available for breakfast and dinner services. Travelers on the run can choose quality food or sundry items from our Made-Market off the lobby. Our delightful DoubleTree Cookies are readily available from our courteous and friendly guest service agents.HiltonRead less",
    "address": "108 Chestnut Street Toronto ON M5G 1R3",
    "imageUrl": "https://content.r9cdn.net/rimg/himg/7c/04/f3/ice-37466-98820555-752445.jpg?width=452&height=400&xhint=1497&yhint=960&crop=true&watermarkheight=28&watermarkpadding=10",
    "amenities": [
      "Indoor pool",
      "Fitness centre",
      "Restaurant",
      "Bar/Lounge",
      "Room service",
      "Free Wi-Fi",
      "Coffee machine",
      "Coffee shop",
      "Business centre",
      "Wi-Fi available in all areas"
    ],
    "allAmenities": [
      "Contactless check-in/check-out",
      "Physical distancing in dining areas",
      "Physical distancing rules",
      "Property is cleaned by professional cleaning companies",
      "CCTV in common areas",
      "Hand sanitizer in guest accommodation and key areas",
      "Screens or physical barriers placed between staff and guests in appropriate areas",
      "Use of cleaning chemicals that are effective against coronavirus",
      "24-hour security",
      "All plates, cutlery, glasses and other tableware have been sanitized",
      "Delivered food is securely covered",
      "Guests can opt out of accommodation cleaning",
      "Staff follow all safety protocols as directed by local authorities",
      "Disinfection of high-touch surfaces",
      "First-aid kit",
      "Enhanced cleaning",
      "Safe",
      "Wi-Fi available in all areas",
      "Internet",
      "Fire extinguisher",
      "Free toiletries",
      "Smoke alarms",
      "Heating",
      "Air-conditioned",
      "Free Wi-Fi",
      "Linens",
      "Towels",
      "Packed lunches",
      "Restaurant",
      "Bar/Lounge",
      "Food can be delivered to guest accommodation",
      "Coffee shop",
      "Minibar",
      "Snack bar",
      "Dining table",
      "Flat-screen TV",
      "Cable or satellite TV",
      "Pay-per-view channels",
      "Radio",
      "CD player",
      "Smartphone dock",
      "TV",
      "Hairdryer",
      "Bathrobe",
      "Private bathroom",
      "Shower",
      "Bathtub",
      "Toilet",
      "Ironing service",
      "Laundry facilities",
      "Laundry service",
      "Iron and ironing board",
      "Beach access",
      "Bicycle rental",
      "Golf",
      "Fax/photocopying",
      "Desk",
      "Fitness centre",
      "ATM on-site",
      "Business centre",
      "Car rental",
      "Wake-up service",
      "Concierge service",
      "Currency exchange on-site",
      "Mini-market on site",
      "Meeting/Banquet facilities",
      "Room service",
      "Tour desk",
      "Express check-out",
      "24hr front desk",
      "Conference rooms",
      "Safety deposit box",
      "Kitchenware",
      "Kitchen",
      "Kitchenette",
      "Dishwasher",
      "Microwave",
      "Stovetop",
      "Refrigerator",
      "Coffee machine",
      "Family rooms",
      "Storage available",
      "Seating area",
      "Slippers",
      "Sofa",
      "Soundproof rooms",
      "Telephone",
      "Carpeted",
      "Hypoallergenic",
      "No smoking",
      "Designated smoking area",
      "Pets allowed on request. Charges may apply.",
      "Disabled Access",
      "Elevator",
      "Allergy-free room",
      "Heated pool",
      "Hot tub",
      "Indoor pool",
      "Massage",
      "Sauna",
      "Babysitting or child care",
      "Kids meals",
      "Kid-friendly buffet",
      "Swimming pool toys",
      "Alarm clock",
      "Wardrobe or closet",
      "Parking"
    ],
    "_class": "com.accommodation.pricing.analysis.model.Hotel"
  },{
    "_id": {
      "$oid": "6572d4a68b1ed834068ebc2f"
    },
    "price": "348",
    "name": "DoubleTree by Hilton Toronto Downtown",
    "location": "not found",
    "url": "https://www.momondo.ca/hotel-search/Chelsea-Hotel,Toronto,Toronto-c11592-h32729-details/2023-12-13/2023-12-14/2adults?psid=hHCkB37OEZ&pm=totaltaxes#overview",
    "reviewDescription": "Good",
    "score": "7.7",
    "reviewCount": "5,372 reviews",
    "noOfguests": "2",
    "city": "Toronto",
    "fromDate": "2023-12-13",
    "toDate": "2023-12-14",
    "overView": "A landmark hotel in the heart of downtown Toronto located at 108 Chestnut St; Toronto in the city’s business hub. Conveniently located close to major Government Offices, Nathan Phillips Square, City Hall, World Class Hospitals, Universities, US Consulate & Diplomatic Missions, Toronto's Eaton Centre, Yonge/Dundas Square, TTC subway, underground PATH, major attractions and points of interest. The hotel features 490 modern non-smoking guest rooms including 34 suites. The standard guestrooms consist of the choice of standard king, queen, or two double beds. The 26 two-room suites boast kitchenettes and separate living area, are ideal for extended stays or guests looking for additional space. The hotel also has 4 Junior Suites which have an open-concept layout with kitchenettes as well as 4 Executive Suites, all of which are located on the 25th and 26th floors. The suites are large enough to accommodate intimate corporate meetings or receptions. The hotel offers a concierge service, uniformed security patrol, secure underground guest parking, and an ATM located in the lobby. Guests can stay connected with complimentary high-speed internet access throughout the hotel and 24 hour open-concept business centre. Maintain your exercise regime in the complimentary 24-hour Precor fitness center, unwind in the sauna or take a dip in the heated indoor swimming pool. Changing facilities are equipped with lockers. A laundry room is situated on the Mezzanine Level for guest convenience. Dine-in or takeout at our new concept on-site Hemisphere's Restaurant for breakfast, lunch or dinner. Relax and enjoy light fare and cocktails with friends or colleagues in our Bistro lounge. Room service is available for breakfast and dinner services. Travelers on the run can choose quality food or sundry items from our Made-Market off the lobby. Our delightful DoubleTree Cookies are readily available from our courteous and friendly guest service agents.HiltonRead less",
    "address": "108 Chestnut Street Toronto ON M5G 1R3",
    "imageUrl": "https://content.r9cdn.net/rimg/himg/7c/04/f3/ice-37466-98820555-752445.jpg?width=452&height=400&xhint=1497&yhint=960&crop=true&watermarkheight=28&watermarkpadding=10",
    "amenities": [
      "Indoor pool",
      "Fitness centre",
      "Restaurant",
      "Bar/Lounge",
      "Room service",
      "Free Wi-Fi",
      "Coffee machine",
      "Coffee shop",
      "Business centre",
      "Wi-Fi available in all areas"
    ],
    "allAmenities": [
      "Contactless check-in/check-out",
      "Physical distancing in dining areas",
      "Physical distancing rules",
      "Property is cleaned by professional cleaning companies",
      "CCTV in common areas",
      "Hand sanitizer in guest accommodation and key areas",
      "Screens or physical barriers placed between staff and guests in appropriate areas",
      "Use of cleaning chemicals that are effective against coronavirus",
      "24-hour security",
      "All plates, cutlery, glasses and other tableware have been sanitized",
      "Delivered food is securely covered",
      "Guests can opt out of accommodation cleaning",
      "Staff follow all safety protocols as directed by local authorities",
      "Disinfection of high-touch surfaces",
      "First-aid kit",
      "Enhanced cleaning",
      "Safe",
      "Wi-Fi available in all areas",
      "Internet",
      "Fire extinguisher",
      "Free toiletries",
      "Smoke alarms",
      "Heating",
      "Air-conditioned",
      "Free Wi-Fi",
      "Linens",
      "Towels",
      "Packed lunches",
      "Restaurant",
      "Bar/Lounge",
      "Food can be delivered to guest accommodation",
      "Coffee shop",
      "Minibar",
      "Snack bar",
      "Dining table",
      "Flat-screen TV",
      "Cable or satellite TV",
      "Pay-per-view channels",
      "Radio",
      "CD player",
      "Smartphone dock",
      "TV",
      "Hairdryer",
      "Bathrobe",
      "Private bathroom",
      "Shower",
      "Bathtub",
      "Toilet",
      "Ironing service",
      "Laundry facilities",
      "Laundry service",
      "Iron and ironing board",
      "Beach access",
      "Bicycle rental",
      "Golf",
      "Fax/photocopying",
      "Desk",
      "Fitness centre",
      "ATM on-site",
      "Business centre",
      "Car rental",
      "Wake-up service",
      "Concierge service",
      "Currency exchange on-site",
      "Mini-market on site",
      "Meeting/Banquet facilities",
      "Room service",
      "Tour desk",
      "Express check-out",
      "24hr front desk",
      "Conference rooms",
      "Safety deposit box",
      "Kitchenware",
      "Kitchen",
      "Kitchenette",
      "Dishwasher",
      "Microwave",
      "Stovetop",
      "Refrigerator",
      "Coffee machine",
      "Family rooms",
      "Storage available",
      "Seating area",
      "Slippers",
      "Sofa",
      "Soundproof rooms",
      "Telephone",
      "Carpeted",
      "Hypoallergenic",
      "No smoking",
      "Designated smoking area",
      "Pets allowed on request. Charges may apply.",
      "Disabled Access",
      "Elevator",
      "Allergy-free room",
      "Heated pool",
      "Hot tub",
      "Indoor pool",
      "Massage",
      "Sauna",
      "Babysitting or child care",
      "Kids meals",
      "Kid-friendly buffet",
      "Swimming pool toys",
      "Alarm clock",
      "Wardrobe or closet",
      "Parking"
    ],
    "_class": "com.accommodation.pricing.analysis.model.Hotel"
  },
  {
    "_id": {
      "$oid": "6572d4a68b1ed834068ebc2f"
    },
    "price": "348",
    "name": "DoubleTree by Hilton Toronto Downtown",
    "location": "not found",
    "url": "https://www.momondo.ca/hotel-search/Chelsea-Hotel,Toronto,Toronto-c11592-h32729-details/2023-12-13/2023-12-14/2adults?psid=hHCkB37OEZ&pm=totaltaxes#overview",
    "reviewDescription": "Good",
    "score": "7.7",
    "reviewCount": "5,372 reviews",
    "noOfguests": "2",
    "city": "Toronto",
    "fromDate": "2023-12-13",
    "toDate": "2023-12-14",
    "overView": "A landmark hotel in the heart of downtown Toronto located at 108 Chestnut St; Toronto in the city’s business hub. Conveniently located close to major Government Offices, Nathan Phillips Square, City Hall, World Class Hospitals, Universities, US Consulate & Diplomatic Missions, Toronto's Eaton Centre, Yonge/Dundas Square, TTC subway, underground PATH, major attractions and points of interest. The hotel features 490 modern non-smoking guest rooms including 34 suites. The standard guestrooms consist of the choice of standard king, queen, or two double beds. The 26 two-room suites boast kitchenettes and separate living area, are ideal for extended stays or guests looking for additional space. The hotel also has 4 Junior Suites which have an open-concept layout with kitchenettes as well as 4 Executive Suites, all of which are located on the 25th and 26th floors. The suites are large enough to accommodate intimate corporate meetings or receptions. The hotel offers a concierge service, uniformed security patrol, secure underground guest parking, and an ATM located in the lobby. Guests can stay connected with complimentary high-speed internet access throughout the hotel and 24 hour open-concept business centre. Maintain your exercise regime in the complimentary 24-hour Precor fitness center, unwind in the sauna or take a dip in the heated indoor swimming pool. Changing facilities are equipped with lockers. A laundry room is situated on the Mezzanine Level for guest convenience. Dine-in or takeout at our new concept on-site Hemisphere's Restaurant for breakfast, lunch or dinner. Relax and enjoy light fare and cocktails with friends or colleagues in our Bistro lounge. Room service is available for breakfast and dinner services. Travelers on the run can choose quality food or sundry items from our Made-Market off the lobby. Our delightful DoubleTree Cookies are readily available from our courteous and friendly guest service agents.HiltonRead less",
    "address": "108 Chestnut Street Toronto ON M5G 1R3",
    "imageUrl": "https://content.r9cdn.net/rimg/himg/7c/04/f3/ice-37466-98820555-752445.jpg?width=452&height=400&xhint=1497&yhint=960&crop=true&watermarkheight=28&watermarkpadding=10",
    "amenities": [
      "Indoor pool",
      "Fitness centre",
      "Restaurant",
      "Bar/Lounge",
      "Room service",
      "Free Wi-Fi",
      "Coffee machine",
      "Coffee shop",
      "Business centre",
      "Wi-Fi available in all areas"
    ],
    "allAmenities": [
      "Contactless check-in/check-out",
      "Physical distancing in dining areas",
      "Physical distancing rules",
      "Property is cleaned by professional cleaning companies",
      "CCTV in common areas",
      "Hand sanitizer in guest accommodation and key areas",
      "Screens or physical barriers placed between staff and guests in appropriate areas",
      "Use of cleaning chemicals that are effective against coronavirus",
      "24-hour security",
      "All plates, cutlery, glasses and other tableware have been sanitized",
      "Delivered food is securely covered",
      "Guests can opt out of accommodation cleaning",
      "Staff follow all safety protocols as directed by local authorities",
      "Disinfection of high-touch surfaces",
      "First-aid kit",
      "Enhanced cleaning",
      "Safe",
      "Wi-Fi available in all areas",
      "Internet",
      "Fire extinguisher",
      "Free toiletries",
      "Smoke alarms",
      "Heating",
      "Air-conditioned",
      "Free Wi-Fi",
      "Linens",
      "Towels",
      "Packed lunches",
      "Restaurant",
      "Bar/Lounge",
      "Food can be delivered to guest accommodation",
      "Coffee shop",
      "Minibar",
      "Snack bar",
      "Dining table",
      "Flat-screen TV",
      "Cable or satellite TV",
      "Pay-per-view channels",
      "Radio",
      "CD player",
      "Smartphone dock",
      "TV",
      "Hairdryer",
      "Bathrobe",
      "Private bathroom",
      "Shower",
      "Bathtub",
      "Toilet",
      "Ironing service",
      "Laundry facilities",
      "Laundry service",
      "Iron and ironing board",
      "Beach access",
      "Bicycle rental",
      "Golf",
      "Fax/photocopying",
      "Desk",
      "Fitness centre",
      "ATM on-site",
      "Business centre",
      "Car rental",
      "Wake-up service",
      "Concierge service",
      "Currency exchange on-site",
      "Mini-market on site",
      "Meeting/Banquet facilities",
      "Room service",
      "Tour desk",
      "Express check-out",
      "24hr front desk",
      "Conference rooms",
      "Safety deposit box",
      "Kitchenware",
      "Kitchen",
      "Kitchenette",
      "Dishwasher",
      "Microwave",
      "Stovetop",
      "Refrigerator",
      "Coffee machine",
      "Family rooms",
      "Storage available",
      "Seating area",
      "Slippers",
      "Sofa",
      "Soundproof rooms",
      "Telephone",
      "Carpeted",
      "Hypoallergenic",
      "No smoking",
      "Designated smoking area",
      "Pets allowed on request. Charges may apply.",
      "Disabled Access",
      "Elevator",
      "Allergy-free room",
      "Heated pool",
      "Hot tub",
      "Indoor pool",
      "Massage",
      "Sauna",
      "Babysitting or child care",
      "Kids meals",
      "Kid-friendly buffet",
      "Swimming pool toys",
      "Alarm clock",
      "Wardrobe or closet",
      "Parking"
    ],
    "_class": "com.accommodation.pricing.analysis.model.Hotel"
  },
  {
    "_id": {
      "$oid": "6572d4a68b1ed834068ebc2f"
    },
    "price": "348",
    "name": "DoubleTree by Hilton Toronto Downtown",
    "location": "not found",
    "url": "https://www.momondo.ca/hotel-search/Chelsea-Hotel,Toronto,Toronto-c11592-h32729-details/2023-12-13/2023-12-14/2adults?psid=hHCkB37OEZ&pm=totaltaxes#overview",
    "reviewDescription": "Good",
    "score": "7.7",
    "reviewCount": "5,372 reviews",
    "noOfguests": "2",
    "city": "Toronto",
    "fromDate": "2023-12-13",
    "toDate": "2023-12-14",
    "overView": "A landmark hotel in the heart of downtown Toronto located at 108 Chestnut St; Toronto in the city’s business hub. Conveniently located close to major Government Offices, Nathan Phillips Square, City Hall, World Class Hospitals, Universities, US Consulate & Diplomatic Missions, Toronto's Eaton Centre, Yonge/Dundas Square, TTC subway, underground PATH, major attractions and points of interest. The hotel features 490 modern non-smoking guest rooms including 34 suites. The standard guestrooms consist of the choice of standard king, queen, or two double beds. The 26 two-room suites boast kitchenettes and separate living area, are ideal for extended stays or guests looking for additional space. The hotel also has 4 Junior Suites which have an open-concept layout with kitchenettes as well as 4 Executive Suites, all of which are located on the 25th and 26th floors. The suites are large enough to accommodate intimate corporate meetings or receptions. The hotel offers a concierge service, uniformed security patrol, secure underground guest parking, and an ATM located in the lobby. Guests can stay connected with complimentary high-speed internet access throughout the hotel and 24 hour open-concept business centre. Maintain your exercise regime in the complimentary 24-hour Precor fitness center, unwind in the sauna or take a dip in the heated indoor swimming pool. Changing facilities are equipped with lockers. A laundry room is situated on the Mezzanine Level for guest convenience. Dine-in or takeout at our new concept on-site Hemisphere's Restaurant for breakfast, lunch or dinner. Relax and enjoy light fare and cocktails with friends or colleagues in our Bistro lounge. Room service is available for breakfast and dinner services. Travelers on the run can choose quality food or sundry items from our Made-Market off the lobby. Our delightful DoubleTree Cookies are readily available from our courteous and friendly guest service agents.HiltonRead less",
    "address": "108 Chestnut Street Toronto ON M5G 1R3",
    "imageUrl": "https://content.r9cdn.net/rimg/himg/7c/04/f3/ice-37466-98820555-752445.jpg?width=452&height=400&xhint=1497&yhint=960&crop=true&watermarkheight=28&watermarkpadding=10",
    "amenities": [
      "Indoor pool",
      "Fitness centre",
      "Restaurant",
      "Bar/Lounge",
      "Room service",
      "Free Wi-Fi",
      "Coffee machine",
      "Coffee shop",
      "Business centre",
      "Wi-Fi available in all areas"
    ],
    "allAmenities": [
      "Contactless check-in/check-out",
      "Physical distancing in dining areas",
      "Physical distancing rules",
      "Property is cleaned by professional cleaning companies",
      "CCTV in common areas",
      "Hand sanitizer in guest accommodation and key areas",
      "Screens or physical barriers placed between staff and guests in appropriate areas",
      "Use of cleaning chemicals that are effective against coronavirus",
      "24-hour security",
      "All plates, cutlery, glasses and other tableware have been sanitized",
      "Delivered food is securely covered",
      "Guests can opt out of accommodation cleaning",
      "Staff follow all safety protocols as directed by local authorities",
      "Disinfection of high-touch surfaces",
      "First-aid kit",
      "Enhanced cleaning",
      "Safe",
      "Wi-Fi available in all areas",
      "Internet",
      "Fire extinguisher",
      "Free toiletries",
      "Smoke alarms",
      "Heating",
      "Air-conditioned",
      "Free Wi-Fi",
      "Linens",
      "Towels",
      "Packed lunches",
      "Restaurant",
      "Bar/Lounge",
      "Food can be delivered to guest accommodation",
      "Coffee shop",
      "Minibar",
      "Snack bar",
      "Dining table",
      "Flat-screen TV",
      "Cable or satellite TV",
      "Pay-per-view channels",
      "Radio",
      "CD player",
      "Smartphone dock",
      "TV",
      "Hairdryer",
      "Bathrobe",
      "Private bathroom",
      "Shower",
      "Bathtub",
      "Toilet",
      "Ironing service",
      "Laundry facilities",
      "Laundry service",
      "Iron and ironing board",
      "Beach access",
      "Bicycle rental",
      "Golf",
      "Fax/photocopying",
      "Desk",
      "Fitness centre",
      "ATM on-site",
      "Business centre",
      "Car rental",
      "Wake-up service",
      "Concierge service",
      "Currency exchange on-site",
      "Mini-market on site",
      "Meeting/Banquet facilities",
      "Room service",
      "Tour desk",
      "Express check-out",
      "24hr front desk",
      "Conference rooms",
      "Safety deposit box",
      "Kitchenware",
      "Kitchen",
      "Kitchenette",
      "Dishwasher",
      "Microwave",
      "Stovetop",
      "Refrigerator",
      "Coffee machine",
      "Family rooms",
      "Storage available",
      "Seating area",
      "Slippers",
      "Sofa",
      "Soundproof rooms",
      "Telephone",
      "Carpeted",
      "Hypoallergenic",
      "No smoking",
      "Designated smoking area",
      "Pets allowed on request. Charges may apply.",
      "Disabled Access",
      "Elevator",
      "Allergy-free room",
      "Heated pool",
      "Hot tub",
      "Indoor pool",
      "Massage",
      "Sauna",
      "Babysitting or child care",
      "Kids meals",
      "Kid-friendly buffet",
      "Swimming pool toys",
      "Alarm clock",
      "Wardrobe or closet",
      "Parking"
    ],
    "_class": "com.accommodation.pricing.analysis.model.Hotel"
  }]

  export default hotelList